version: '3'

services:
  run-up-api:
    container_name: run-up-api
    build: .
    environment:
      - PORT=3031
      - REDIS_URL=redis://run-up-redis:6379
    ports:
    - "3031:3031"
    depends_on:
      - run-up-redis

  run-up-redis:
    image: redis
    container_name: run-up-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  redis-data:
